### ISSUE TITLE
Footer on top of post page

### ISSUE THREAD

**Issue by saifulmuhajir** [ColeTownsend/Balzac-for-Jekyll#50]
Running locally with Jekyll 3.8.4 and the footer is on top of the posts. I didn't find anything with error from console browsers.

![screenshot_20181013_144408](https://user-images.githubusercontent.com/912198/46905612-a2003780-cef6-11e8-8919-05cdbf9a3dc0.png)

Can you help with this in any way? Thanks

**Comment by saifulmuhajir** [comment]
Found this:
```css
#bump {
    min-height: 100%;
    height: auto;
    margin: 0 auto ($footerHeight * -1);
}
```

Decided to remove the `($footerHeight * -1)` and everything looks green now.
